{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "localdeps.postgresName" . }}
  labels:
    {{- include "localdeps.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
  annotations:
    checkov.io/skip1: CKV_K8S_21=helm template khong truyen -n nen render ra namespace default; cai dat that luon co -n insighthub-local - xem SPEC.md muc 13
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: {{ .Values.postgres.service.port }}
      targetPort: postgres
      protocol: TCP
  selector:
    {{- include "localdeps.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
{{- end }}
