#!/usr/bin/env python3
"""Wrap prometheus-rules/anomaly-rules.yaml in a PrometheusRule CRD (single source of truth)."""
import pathlib
import sys

import yaml

here = pathlib.Path(__file__).resolve().parent
rules = yaml.safe_load((here / "prometheus-rules" / "anomaly-rules.yaml").read_text())
crd = {
    "apiVersion": "monitoring.coreos.com/v1",
    "kind": "PrometheusRule",
    "metadata": {
        "name": "insighthub-anomaly",
        "namespace": "monitoring",
        "labels": {"release": "kube-prom-stack", "app.kubernetes.io/name": "insighthub"},
    },
    "spec": {"groups": rules["groups"]},
}
out = here / "k8s" / "prometheusrule-insighthub.yaml"
out.write_text("# Generated by observability/render-prometheusrule.py - do not edit by hand.\n"
               + yaml.safe_dump(crd, sort_keys=False, width=200))
sys.stdout.write(str(out) + "\n")
