apiVersion: v1
kind: Service
metadata:
  name: {{ include "insighthub.webServiceName" . }}
  labels:
    {{- include "insighthub.componentLabels" (dict "ctx" . "component" "web") | nindent 4 }}
  {{- with .Values.web.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.web.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "insighthub.componentSelectorLabels" (dict "ctx" . "component" "web") | nindent 4 }}
